### ISSUE TITLE
Structural reliability analysis

### ISSUE THREAD

**Issue by nilswagner** [pystra/pystra#1]
I am new to pyre. 

I obtain an error when I run the following script. 

File "olsson.py", line 30, in example_limitstatefunction
  x0[0] = X1
ValueError: setting an array element with a sequence.

How can I resolve the problem.

import numpy as np

from scipy.linalg import solve
import pyre as pyre
# 
# Example taken from
# 
# On Latin hypercube sampling for structural reliability analysis
# Structural Safety 25 pp. 47--68 (2003)
# Example I

def K(x):
    """ Stiffness matrix """
    tmp = np.zeros((2,2),np.float64)
    tmp[0,0] = x[0]+x[1]+x[2]+x[3]
    tmp[0,1] = -x[2]-x[3]
    tmp[1,0] = -x[2]-x[3]
    tmp[1,1] = x[2]+x[3]
    return tmp

def f(x):
    """ Load vector """
    tmp = np.zeros(2,np.float64)
    tmp[0] = x[4]
    tmp[1] = x[5]
    return tmp

def example_limitstatefunction(X1,X2,X3,X4,X5,X6):
    x0 = np.zeros(6,np.float64)
    print X1,type(X1)
    x0[0] = X1
    x0[1] = X2
    x0[2] = X3
    x0[3] = X4
    x0[4] = X5
    x0[5] = X6
    # Displacements
    u = solve(K(x0),f(x0))

```
return 2.17-u[1]
```

limit_state = pyre.LimitState(example_limitstatefunction)

options = pyre.AnalysisOptions()

stochastic_model = pyre.StochasticModel()
stochastic_model.addVariable( pyre.Lognormal('X1',10.,2.) )
stochastic_model.addVariable( pyre.Lognormal('X2',10.,2.) )
stochastic_model.addVariable( pyre.Lognormal('X3',10.,2.) )
stochastic_model.addVariable( pyre.Lognormal('X4',10.,2.) )
stochastic_model.addVariable( pyre.Lognormal('X5',10.,2.) )
stochastic_model.addVariable( pyre.Lognormal('X6',10.,2.) )

Analysis = pyre.Form(analysis_options=options, stochastic_model=stochastic_model, limit_state=limit_state)

**Comment by brunosalves** [comment]
Hey nilswagner,

A believe the problem lies on the type of variable you are using in your functions. When PyRe calls "example_limitstatefunction" the input data are numpy.arrays, then, X1, for example, is an array with shape equal to (n, 1) where 'n' is the number of rows in the array (which is variable, by the way).

I believe that what you need to do in order for your example to work properly is to rewrite these functions so they can work with the input data mentioned. Otherwise you'll face a problem either when defining the matrices K and F, or when trying to run 'solve'.
